export class Actions {
    public static CHANGE_ROLE: string = "Change Role"
    public static VIEW_BILL_DATA: string = "View Bill Data"
    public static MANAGE_BILL_DATA: string = "Manage Bill Data"
    public static VALIDATE_BILL_DATA: string = "Validate Bill Data"
    public static VIEW_BILL_STATUS: string = "View Bill Status"
    public static CREATE_PAYMENT_REQUEST: string = "Create Payment Request"
    public static APPROVE_PAYMENT_REQUEST: string = "Approve Payment Request"
    public static INITIATE_PAYMENT: string = "Initiate Payment"
    public static VIEW_REQUEST_STATUS: string = "View Request Status"
    public static MANAGE_ACCOUNT: string = "Manage Account"
    public static CREATE_OTHER_ACCOUNT_USER: string = "Create Admin User (Non Owner Account)"
    public static CREATE_USER: string = "Create User (Owner Account)"
    public static EDIT_OTHER_ACCOUNT_USER: string = "Edit Admin User (Non Owner Account)"
    public static EDIT_USER: string = "Edit User (Owner Account)"
    public static BAR_OTHER_ACCOUNT_USER: string = "Bar Admin User (Non Owner Account)"
    public static BAR_USER: string = "Bar User (Owner Account)"
    public static EDIT_PERMISSION: string = "Change Permission"
    public static DELETE_OTHER_ACCOUNT_USER: string = "Delete Admin User (Non Owner Account)"
    public static DELETE_USER: string = "Delete User (Owner Account)"
    public static LIST_OTHER_ACCOUNT_USERS: string = "List Admin Users (Non Owner Account)"
    public static LIST_USERS: string = "List Users (Owner Account)"
    public static MANAGE_ROLE: string = "Manage Role"
    public static CHECK_BALANCE: string = "Check Balance"
    public static VIEW_TRANSACTION_REPORT: string = "View Transaction Report"
    public static VIEW_PREPAID_TOKEN_STATUS: string = "View Prepaid Token Status"
    public static SEND_TOKEN_SMS: string = "Send Token SMS"
}